name: Deploy

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 15,45 * * * *

jobs:
  sync:
    runs-on: ubuntu-latest

    outputs:
      update: ${{ steps.sync.outputs.update }}

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Check out dist
        uses: actions/checkout@v3
        with:
          ref: dist
          path: dist

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: yarn

      - name: Sync
        id: sync
        run: yarn sync

      - name: Bundle
        if: ${{ steps.sync.outputs.update }}
        run: yarn bundle

      - name: Deploy assets
        if: ${{ steps.sync.outputs.update }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

      - name: Remove files
        if: ${{ steps.sync.outputs.update }}
        run: |
          rm -rf dist/plugins

      - name: Deploy index
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ steps.sync.outputs.update }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: dist
          user_name: GitHub Actions
          user_email: actions@github.com
          force_orphan: true
          enable_jekyll: true
          commit_message: '[skip ci] deploy'

  deploy:
    if: ${{ needs.sync.outputs.update }}
    needs:
      - sync

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.pages_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v1
