name: Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: 15/30 * * * *

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Check out dist
        uses: actions/checkout@v3
        with:
          ref: dist
          path: dist

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: yarn

      - name: Generate
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: dist
          force_orphan: true
          enable_jekyll: true
          commit_message: '[skip ci] deploy'
